# -*- coding: utf-8 -*-
"""Hamoye Stage A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fkrgc9PZMv3TqeYBoPU7rptE31GMWl7a
"""

#checking the summary of the dataset
import pandas as pd
url='http://bit.ly/HDSC-Dataset'
fuel_data = pd.read_csv(url) 
fuel_data.describe(include='all')



#checking the features with missing values and total number of missing values
fuel_data.isnull().sum() 
fuel_unit has a total of 180 missing values

#dropping rows with missing values
#fuel_data.dropna(axis=0,inplace=True)

#fuel_data['fuel_unit'].count()

#checking for the correlation values
fuel_data.corr()
fuel_qty_burned and fuel_mmbtu_per_unit has the second and lowest correlation with the fuel cost per unit burned

#average fuel cost per unit delivered
fuel_data['fuel_cost_per_unit_delivered'].mean()

#groupby report year
fuel_data.groupby(['report_year']).first()

#checking for the year with the highest average cost per unit delivered
grouped_data1=fuel_data.groupby('report_year').agg({'fuel_cost_per_unit_delivered':['mean','min','max']})
grouped_data1
#year with highest average cost per unit delivered is 1997

#checking for the percentage change in fuel cost per unit burned for coal
grouped_data2=fuel_data.groupby(['fuel_type_code_pudl','report_year']).agg({'fuel_cost_per_unit_burned':['sum']})
grouped_data2
#Percentage change in fuel cost per unit burned for coal between year 1998 and 1994=((11851.690-14809.322)/(11851.690+14809.322))*100=11%

#checking for the average fuel cost per unit burned per year
grouped_data3=fuel_data.groupby(['fuel_type_code_pudl']).agg({'fuel_cost_per_unit_burned':['mean']})
grouped_data3
#The fuel type with the lowest average fuel cost per unit burned is waste.

#skewness for fuel quantity burned
fuel_data['fuel_qty_burned'].skew()

#kurtosis for fuel quantity burned
fuel_data['fuel_qty_burned'].kurtosis()

#standard deviation for fuel_mmbtu_per_unit
import statistics
fuel_data['fuel_mmbtu_per_unit'].astype(int)
statistics.stdev(fuel_data['fuel_mmbtu_per_unit'])

#75 percentile for fuel_mmbtu_per_unit
import numpy as np
np.percentile(fuel_data['fuel_mmbtu_per_unit'],75)

